require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

  TargetRailsVersion: 5.2

  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - '**/spec_helper.rb'

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/TrailingBlankLines:
  EnforcedStyle: final_blank_line

Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Lint/Debugger:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Naming/UncommunicativeMethodParamName:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/LambdaCall:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'spec/**/*'

