require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

  TargetRailsVersion: 5.2

  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - '**/spec_helper.rb'

Layout/TrailingBlankLines:
  EnforcedStyle: final_blank_line

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

Style/HashSyntax:
  Exclude:
    - 'Rakefile'

