AllCops:
  NewCops: enable

  TargetRubyVersion: 2.6

  TargetRailsVersion: 5.2

  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - '**/spec_helper.rb'

Layout/DotPosition:
  EnforcedStyle: leading

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/TrailingEmptyLines:
  EnforcedStyle: final_blank_line

Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Lint/Debugger:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/LambdaCall:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'spec/**/*'

